# Generated by Django 4.2.20 on 2025-03-31 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('default_address', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('typology', models.CharField(blank=True, choices=[('1', 'dealer'), ('2', 'customer')], max_length=10, null=True)),
                ('restaurant', models.ManyToManyField(to='restaurants.restaurant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
