# Generated by Django 4.2.20 on 2025-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='typology',
            field=models.CharField(choices=[('de', 'dealer'), ('cu', 'customer')], default='cu', max_length=10),
        ),
    ]
