# Generated by Django 4.2.20 on 2025-04-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='estimated_time',
            new_name='estimated_timee',
        ),
    ]
