# Generated by Django 4.2.20 on 2025-04-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_estimated_time_delivery_estimated_timee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='estimated_timee',
            new_name='estimated_time',
        ),
    ]
