name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"
        env:
          POSTGRES_HOST: "localhost"
          POSTGRES_PORT: 5432
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          CELERY_RESULT_BACKEND: "redis://redis:6379/0"
          CELERY_BROKER_URL: "redis://redis:6379/0"
          REDIS_HOST: "redis"

      - name: Execute tests in the running services
        run: |
          docker compose run web python manage.py test
